blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
        url(r'^$', views.post_list.as_view(), name='post_list'),
        url(r'^post/(?P<pk>\d+)/$', views.post_detail.as_view(), name='post_detail'),
        url(r'^post/new/$', views.post_new, name='post_new'),
        url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
        url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
        url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
        url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
        url(r'^post/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
        url(r'^post/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
        url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
        ]

mysite/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views

from mysite.views import HomeView

urlpatterns = [
    #url(r'', include('blog.urls')),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page':'/'}),
    url(r'^photo/', include('photo.urls', namespace='photo')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
) + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
    )


#    url(r'^static/(?P<path>.*)$', staticfiles.views.serve),
#    url(r'^dedia/(?P<path>.*)$', 'django.views.static.serve', {
#        'document_root': settings.MEDIA_ROOT,
#        }),

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lan="ko">

<head>
    <title>My First Blog</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <!--
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    -->
    <link rel="stylesheet" href="/static/open-iconic/font/css/open-iconic-bootstrap.css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link rel="stylesheet" href="{% block extrastyle %}{% endblock %}">
    <script src = "https://cdn.ckeditor.com/4.7.3/standard/ckeditor.js"></script>
</head>

<body>
    <nav class="navbar navbar-expand-md fixed-top navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Menu</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/photo/">Photo</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <div class="page-header">
        {% if user.is_authenticated %}
            <a  href="{% url 'blog:post_new' %}" class="top-menu"><span class="oi oi-plus"></span></a>
            <a  href="{% url 'blog:post_draft_list' %}" class="top-menu"><span class="oi oi-pencil"></span></a>
            <p class="top-menu">Hello {{ user.username }} <small>(<a href="{% url 'logout' %}">Log out</a>)</small></p>
        {% else %}
            <!--
            <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
            -->
            <a href="{% url 'login' %}" class="top-menu"><span class="oi oi-lock-locked"</span></a>
        {% endif %}
        <h1><a href="/">Django Blog</a></h1>
    </div>

    <div class="content container-fluid">
        <div class="row">
            <div class="col-md-8 ml-auto mr-auto">
                {% block  content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

</html>

templates/blog_base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lan="ko">

<head>
    <title>My First Blog</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <!--
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    -->
    <link rel="stylesheet" href="/static/open-iconic/font/css/open-iconic-bootstrap.css">
    <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link rel="stylesheet" href="{% block extrastyle %}{% endblock %}">
    <script src = "https://cdn.ckeditor.com/4.7.3/standard/ckeditor.js"></script>
</head>

<body>

    <div class="page-header">
        {% if user.is_authenticated %}
            <a  href="{% url 'blog:post_new' %}" class="top-menu"><span class="oi oi-plus"></span></a>
            <a  href="{% url 'blog:post_draft_list' %}" class="top-menu"><span class="oi oi-pencil"></span></a>
            <p class="top-menu">Hello {{ user.username }} <small>(<a href="{% url 'logout' %}">Log out</a>)</small></p>
        {% else %}
            <!--
            <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
            -->
            <a href="{% url 'login' %}" class="top-menu"><span class="oi oi-lock-locked"</span></a>
        {% endif %}
        <h1><a href="/blog/">Spacehover's Blog</a></h1>
    </div>

    <div class="content container-fluid">
        <div class="row">
            <div class="col-md-8 ml-auto mr-auto">
                {% block  content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

</html>

templates/home.html
{% load staticfiles %}
<!DOCTYPE html>
<!-- saved from url=(0049)https://getbootstrap.com/docs/4.0/examples/cover/ -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://getbootstrap.com/favicon.ico">

    <title>My Website Cover</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/cover.css" rel="stylesheet">
  <style id="style-1-cropbar-clipper">/* Copyright 2014 Evernote Corporation. All rights reserved. */
.en-markup-crop-options {
    top: 18px !important;
    left: 50% !important;
    margin-left: -100px !important;
    width: 200px !important;
    border: 2px rgba(255,255,255,.38) solid !important;
    border-radius: 4px !important;
}


.en-markup-crop-options div div:first-of-type {
    margin-left: 0px !important;
}
</style></head>

  <body>
	<div class="card bg-dark text-white">
	  <div class="card-body">
	    <h4 class="card-title">Home</h4>
	    <p class="card-text">There are so many stars. I will belong to one of them.</p>
        <p class="card-text"><small class="text-muted"><a href="/blog/">Let's start journey.</a></small></p>
	  </div>
      <!--
 	  <img class="card-img-bottom" src="/media/images/benjamin-davies-361151.png" alt="Card image">
        -->
	</div>


        <footer class="mastfoot">
            <div class="inner">
              <p>Spacehover website <a href="https://spacehover.net/">SPACEHOVER</a>, by spacehover</p>
            </div>
          </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/static/css/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="/static/css/popper.min.js"></script>
    <script src="/static/css/bootstrap.min.js"></script>

</body></html>